<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Frontend\" />
    <Folder Include="Models\" />
    <Folder Include="Prompts\" />
    <Folder Include="Services\" />
    <None Include="Prompts\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.4.1" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.4.1" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.74.0" />
    <PackageReference Include="Pinecone.Client" Version="4.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);SKEXP0050</NoWarn>
  </PropertyGroup>
</Project>
